### ISSUE TITLE
File path issues

### ISSUE THREAD

**Issue by jnoske** [tommyhuangthu/UniDesign#2]
Hi,

I seem to have some issues with file paths when trying to run UniDesign.

The program works fine when I use relative path to the binary (./UniDesign) and I am in the UniDesign directory, but not absolute paths (/abc/ab/UniDesign).

The same is for library and wread subfolders which cannot be found in my directory when I execute the binary from outside of the program directory.

I would be happy to get some suggestions.

Best,
Jakob

**Comment by tommyhuangthu** [comment]
Hello Jakob,

Could you provide more details on the command that you're running and show the error messages you have? I used the absolute paths as well, but I did not encounter the problems as you mentioned.

Best wishes,
Xiaoqiang
________________________________
From: Jakob Noske ***@***.***>
Sent: Saturday, March 30, 2024 9:38
To: tommyhuangthu/UniDesign ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tommyhuangthu/UniDesign] File path issues (Issue #2)


Hi,

I seem to have some issues with file paths when trying to run UniDesign.

The program works fine when I use relative path to the binary (./UniDesign) and I am in the UniDesign directory, but not absolute paths (/abc/ab/UniDesign).

The same is for library and wread subfolders which cannot be found in my directory when I execute the binary from outside of the program directory.

I would be happy to get some suggestions.

Best,
Jakob

**Comment by jnoske** [comment]
Hello Xiaoqiang,

Yes the command looks something like this /abc/ab/UniDesign --command=RepairStructure --pdb=xxx.pdb

The output I am getting is: Aborted (core dumped)

Even when I am just trying to run /abc/ab/UniDesign --help.

However when I am inside the directory of UniDesign everything seems to work fine.

Best,
Jakob

**Comment by tommyhuangthu** [comment]
Thank you for the info, Jakob. I think you need to type UniDesign twice, e.g., use /abc/ab/UniDesign/UniDesign. Note that the first UniDesign is the folder, the second UniDesign is the executable.

When you are inside the directory of UniDesign, definitely you only need to type UniDesign once as: ./UniDesign ...

Hope this can resolve your problem.


Best wishes,
Xiaoqiang
________________________________

**Comment by jnoske** [comment]
Sorry my mistake. I am typing /abc/ab/UniDesign/UniDesign to execute the binary that was a typo in my response.

Best,
Jakob

**Comment by tommyhuangthu** [comment]
Then it is interesting that you have such an issue. Both relative and absolute paths work fine on my PC and clusters. So, I guess it should not be a problem from the program itself.

Best wishes,
Xiaoqiang

**Comment by jnoske** [comment]
Ok, maybe it is a problem related to my system then. 
Interestingly, I dont experience it when I am trying to run EvoEF.
But I experience it with EvoEF2 and UniDesign.

Thank you for the help anyway!
